baseURL = "https://justin.searls.co"
languageCode = "en-us"
title = "justin.searls.co"
theme = "ultralight"
pygmentsUseClasses = true
pygmentsCodeFences = true
rssLimit = 100
copyright = "Copyright Justin Searls. All rights reserved."

[author]
  name = "Justin Searls"
  email = "justin@searls.co"

[blackfriday]
  smartypants = false

[params]
  TwitterName = "searls"
  GithubName = "searls"
  Email = "justin@searls.co"
