baseURL = "https://justin.searls.co"
languageCode = "en-us"
title = "searls"
theme = "ultralight"
pygmentsUseClasses = true
pygmentsCodeFences = true

[blackfriday]
  smartypants = false

[params]
  TwitterName = "searls"
  GithubName = "searls"
  Email = "justin@searls.co"
